function [ T ]  = TorqueCalcPiston(Fp,theta2)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  FUNCTION NAME: TorqueCalcPiston
%
%  PURPOSE: Computes the torque generated by the force on the piston of a
%  strirling engine
%
%  INPUT: 
% Fp - Force on piston [N]
% theta2 - Crank angle position [rad]
% 
%  OUTPUT: 
% T - Torque [N]
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%  AUTHOR: Project 3 Group 8
%  DATE: 12/3/22
%
%  DESCRIPTION OF LOCAL VARIABLES:
% phi- Connecting rod angle from the vertical axis [rad]
%
%  FUNCTIONS CALLED
%
%  START OF EXECUTABLE CODE
%


T=zeros(1,361); %initialize array for torque
phi=zeros(1,361);%initialize array for angle phi

for n=1:361
    phi(1,n)=abs(asind(((cosd(theta2(1,n))*0.0138))/(0.046)));
end

for z=1:361
    F=force_piston(1,z);
    theta=theta2(1,z);


if theta >= 0 && theta <= 90 %Check to see if driver is in quadrant 1
    F_x=(Fp*cosd(phi(1,z))*0.046)/
    

elseif theta2 >90 && theta2 <= 180 %Check to see if driver is in quadrant 2
    
elseif theta2 >180 && theta2 <= 270
    

elseif theta2 >270 && theta2 <= 360
   
end

end

